; This file was auto-generated by drush_make
core = 6.x

api = 2
projects[drupal][version] = "6.22"

; Modules
projects[admin_menu][version] = "1.8"

projects[devel][version] = "1.26"

projects[rules][version] = "1.4"

projects[userpoints][version] = "1.2"

projects[views][version] = "2.12"

projects[regcode][version] = "2.7"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[regcode_block][download][type] = "git"
projects[regcode_block][download][url] = "https://esclapes@github.com/esclapes/regcode_block.git"
projects[regcode_block][type] = "module"
